### ISSUE TITLE
atmosphere fog

### ISSUE THREAD

**Issue by epb-644** [gaeaplus/gaeaplus#5]
Is there a way to disable the atmosphere fog in the current version? I'm not sure if fog is the correct term... I'm talking about the bluish filter that is applied, particularly at higher elevations. Thanks!

**Comment by vcucek** [comment]
It is called aerial perspective.
To disable aerial perspective use scene controller property listener.

For example:
<code>wwd.getSceneController().firePropertyChange(AvKeyExt.ENABLE_ATMOSPHERE_WITH_AERIAL_PERSPECTIVE, true, false);</code>

**Comment by epb-644** [comment]
I tried that, but then the globe appears almost completely dark. Is this the desired behavior? (Btw only I'm being pesky because your software is quite beautiful, and we're anxious to use it. :)

**Comment by vcucek** [comment]
Can you please attach screenshot and console output. I will try to fix the problem when i finish my current work.
If it turns out that the ploblem occures only on ATI graphic chipset it will take much longer, because i still don't have any ATI graphic card at my disposal.

**Comment by epb-644** [comment]
Here you go. I'm actually running a GeForce GTX 560.

![gaea](https://f.cloud.github.com/assets/1317326/1043466/460c3f3a-0ffe-11e3-8f00-c258410ca2f3.png)

"C:\Program Files\Java\jdk1.7.0_07\bin\java" -Didea.launcher.port=7537 "-Didea.launcher.bin.path=C:\Program Files (x86)\JetBrains\IntelliJ IDEA 12.1\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.7.0_07\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.7.0_07\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.7.0_07\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.7.0_07\jre\lib\jce.jar;C:\Program Files\Java\jdk1.7.0_07\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.7.0_07\jre\lib\jfxrt.jar;C:\Program Files\Java\jdk1.7.0_07\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.7.0_07\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.7.0_07\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.7.0_07\jre\lib\resources.jar;C:\Program Files\Java\jdk1.7.0_07\jre\lib\rt.jar;C:\Program Files\Java\jdk1.7.0_07\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.7.0_07\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.7.0_07\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.7.0_07\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.7.0_07\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.7.0_07\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.7.0_07\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.7.0_07\jre\lib\ext\zipfs.jar;C:\Users\eburns-admin\Downloads\gaeaplus-master\out\production\gaeaplus-master;C:\Users\eburns-admin\Downloads\gaeaplus-master\lib\gluegen-rt-natives-windows-i586.jar;C:\Users\eburns-admin\Downloads\gaeaplus-master\lib\gluegen-rt.jar;C:\Users\eburns-admin\Downloads\gaeaplus-master\lib\jogl-all-natives-macosx-universal.jar;C:\Users\eburns-admin\Downloads\gaeaplus-master\lib\jogl-all-natives-linux-amd64.jar;C:\Users\eburns-admin\Downloads\gaeaplus-master\lib\jogl-all-natives-windows-amd64.jar;C:\Users\eburns-admin\Downloads\gaeaplus-master\lib\jogl-all.jar;C:\Users\eburns-admin\Downloads\gaeaplus-master\lib\jogl-all-natives-linux-i586.jar;C:\Users\eburns-admin\Downloads\gaeaplus-master\lib\gluegen-rt-natives-linux-i586.jar;C:\Users\eburns-admin\Downloads\gaeaplus-master\lib\gluegen-rt-natives-windows-amd64.jar;C:\Users\eburns-admin\Downloads\gaeaplus-master\lib\plugin.jar;C:\Users\eburns-admin\Downloads\gaeaplus-master\lib\gluegen-rt-natives-macosx-universal.jar;C:\Users\eburns-admin\Downloads\gaeaplus-master\lib\jogl-all-natives-windows-i586.jar;C:\Users\eburns-admin\Downloads\gaeaplus-master\lib\gluegen-rt-natives-linux-amd64.jar;C:\Users\eburns-admin\Downloads\gaeaplus-master\lib\gdal.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA 12.1\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain si.xlab.gaea.examples.ApplicationLightingFull
Aug 28, 2013 10:21:45 AM si.xlab.gaea.core.shaders.BasicGLSLCompiler defineSupportedShaders
INFO: Supported shader profiles: 
#define v110
#define v120
#define v130
#define v140
#define v150

Aug 28, 2013 10:21:45 AM si.xlab.gaea.core.shaders.BasicGLSLCompiler loadProgram
INFO: Compiling shader: /C:/Users/eburns-admin/Downloads/gaeaplus-master/out/production/gaeaplus-master/si/xlab/gaea/core/shaders/data/TerrainNormal.glsl
Aug 28, 2013 10:21:45 AM si.xlab.gaea.core.shaders.BasicShaderFactory buildGLSLShader
INFO: Shader loaded: /C:/Users/eburns-admin/Downloads/gaeaplus-master/out/production/gaeaplus-master/si/xlab/gaea/core/shaders/data/TerrainNormal.glsl
Aug 28, 2013 10:21:47 AM si.xlab.gaea.core.shaders.BasicGLSLCompiler loadProgram
INFO: Compiling shader: /C:/Users/eburns-admin/Downloads/gaeaplus-master/out/production/gaeaplus-master/si/xlab/gaea/core/shaders/data/SurfaceTileShader.glsl
Aug 28, 2013 10:21:47 AM si.xlab.gaea.core.shaders.BasicShaderFactory buildGLSLShader
INFO: Shader loaded: /C:/Users/eburns-admin/Downloads/gaeaplus-master/out/production/gaeaplus-master/si/xlab/gaea/core/shaders/data/SurfaceTileShader.glsl
Aug 28, 2013 10:21:47 AM si.xlab.gaea.core.shaders.BasicGLSLShader$ParameterCache getParameter
WARNING: In shader: /C:/Users/eburns-admin/Downloads/gaeaplus-master/out/production/gaeaplus-master/si/xlab/gaea/core/shaders/data/SurfaceTileShader.glsl ShaderParameter: exaggeration NOT FOUND or NOT USED!
Aug 28, 2013 10:21:47 AM si.xlab.gaea.core.shaders.BasicGLSLShader$ParameterCache getParameter
WARNING: In shader: /C:/Users/eburns-admin/Downloads/gaeaplus-master/out/production/gaeaplus-master/si/xlab/gaea/core/shaders/data/SurfaceTileShader.glsl ShaderParameter: eyeToWorld NOT FOUND or NOT USED!
Aug 28, 2013 10:21:47 AM si.xlab.gaea.core.shaders.BasicGLSLShader$ParameterCache getParameter
WARNING: In shader: /C:/Users/eburns-admin/Downloads/gaeaplus-master/out/production/gaeaplus-master/si/xlab/gaea/core/shaders/data/SurfaceTileShader.glsl ShaderParameter: u_drawDistance NOT FOUND or NOT USED!
Aug 28, 2013 10:21:47 AM si.xlab.gaea.core.shaders.BasicGLSLShader$ParameterCache getParameter
WARNING: In shader: /C:/Users/eburns-admin/Downloads/gaeaplus-master/out/production/gaeaplus-master/si/xlab/gaea/core/shaders/data/SurfaceTileShader.glsl ShaderParameter: normalFactor NOT FOUND or NOT USED!
Aug 28, 2013 10:21:47 AM si.xlab.gaea.core.shaders.BasicGLSLShader$ParameterCache getParameter
WARNING: In shader: /C:/Users/eburns-admin/Downloads/gaeaplus-master/out/production/gaeaplus-master/si/xlab/gaea/core/shaders/data/SurfaceTileShader.glsl ShaderParameter: texelSize NOT FOUND or NOT USED!
Aug 28, 2013 10:21:47 AM si.xlab.gaea.core.shaders.BasicGLSLShader$ParameterCache getParameter
WARNING: In shader: /C:/Users/eburns-admin/Downloads/gaeaplus-master/out/production/gaeaplus-master/si/xlab/gaea/core/shaders/data/SurfaceTileShader.glsl ShaderParameter: sector NOT FOUND or NOT USED!
Aug 28, 2013 10:21:47 AM si.xlab.gaea.core.shaders.BasicGLSLShader$ParameterCache getParameter
WARNING: In shader: /C:/Users/eburns-admin/Downloads/gaeaplus-master/out/production/gaeaplus-master/si/xlab/gaea/core/shaders/data/SurfaceTileShader.glsl ShaderParameter: texelScale NOT FOUND or NOT USED!
Aug 28, 2013 10:21:47 AM si.xlab.gaea.core.shaders.BasicGLSLCompiler printGLLog
SEVERE: OpenGL error number: 1282 description: no error
Aug 28, 2013 10:21:47 AM si.xlab.gaea.core.shaders.BasicGLSLCompiler loadProgram
INFO: Compiling shader: /C:/Users/eburns-admin/Downloads/gaeaplus-master/out/production/gaeaplus-master/si/xlab/gaea/core/shaders/data/SlopeLayer.glsl
Aug 28, 2013 10:21:47 AM si.xlab.gaea.core.shaders.BasicShaderFactory buildGLSLShader
INFO: Shader loaded: /C:/Users/eburns-admin/Downloads/gaeaplus-master/out/production/gaeaplus-master/si/xlab/gaea/core/shaders/data/SlopeLayer.glsl
Aug 28, 2013 10:21:47 AM si.xlab.gaea.core.shaders.BasicGLSLCompiler printGLLog
SEVERE: OpenGL error number: 1282 description: no error
Aug 28, 2013 10:21:47 AM si.xlab.gaea.core.shaders.BasicGLSLCompiler loadProgram
INFO: Compiling shader: /C:/Users/eburns-admin/Downloads/gaeaplus-master/out/production/gaeaplus-master/si/xlab/gaea/core/shaders/data/TerrainLighting_1.glsl
Aug 28, 2013 10:21:47 AM si.xlab.gaea.core.shaders.BasicShaderFactory buildGLSLShader
INFO: Shader loaded: /C:/Users/eburns-admin/Downloads/gaeaplus-master/out/production/gaeaplus-master/si/xlab/gaea/core/shaders/data/TerrainLighting_1.glsl
Aug 28, 2013 10:21:47 AM si.xlab.gaea.core.shaders.BasicGLSLCompiler loadProgram
INFO: Compiling shader: /C:/Users/eburns-admin/Downloads/gaeaplus-master/out/production/gaeaplus-master/si/xlab/gaea/core/shaders/data/Atmosphere_1.glsl
Aug 28, 2013 10:21:47 AM si.xlab.gaea.core.shaders.BasicShaderFactory buildGLSLShader
INFO: Shader loaded: /C:/Users/eburns-admin/Downloads/gaeaplus-master/out/production/gaeaplus-master/si/xlab/gaea/core/shaders/data/Atmosphere_1.glsl
Aug 28, 2013 10:21:47 AM si.xlab.gaea.core.shaders.BasicGLSLShader$ParameterCache getParameter
WARNING: In shader: /C:/Users/eburns-admin/Downloads/gaeaplus-master/out/production/gaeaplus-master/si/xlab/gaea/core/shaders/data/Atmosphere_1.glsl ShaderParameter: exposure NOT FOUND or NOT USED!
Aug 28, 2013 10:21:47 AM si.xlab.gaea.core.shaders.BasicGLSLCompiler loadProgram
INFO: Compiling shader: /C:/Users/eburns-admin/Downloads/gaeaplus-master/out/production/gaeaplus-master/si/xlab/gaea/core/shaders/data/IntensityFilter.glsl
Aug 28, 2013 10:21:47 AM si.xlab.gaea.core.shaders.BasicShaderFactory buildGLSLShader
INFO: Shader loaded: /C:/Users/eburns-admin/Downloads/gaeaplus-master/out/production/gaeaplus-master/si/xlab/gaea/core/shaders/data/IntensityFilter.glsl
Aug 28, 2013 10:21:47 AM si.xlab.gaea.core.shaders.BasicGLSLCompiler loadProgram
INFO: Compiling shader: /C:/Users/eburns-admin/Downloads/gaeaplus-master/out/production/gaeaplus-master/si/xlab/gaea/core/shaders/data/Blure7V.glsl
Aug 28, 2013 10:21:47 AM si.xlab.gaea.core.shaders.BasicShaderFactory buildGLSLShader
INFO: Shader loaded: /C:/Users/eburns-admin/Downloads/gaeaplus-master/out/production/gaeaplus-master/si/xlab/gaea/core/shaders/data/Blure7V.glsl
Aug 28, 2013 10:21:47 AM si.xlab.gaea.core.shaders.BasicGLSLCompiler loadProgram
INFO: Compiling shader: /C:/Users/eburns-admin/Downloads/gaeaplus-master/out/production/gaeaplus-master/si/xlab/gaea/core/shaders/data/Blure7H.glsl
Aug 28, 2013 10:21:47 AM si.xlab.gaea.core.shaders.BasicShaderFactory buildGLSLShader
INFO: Shader loaded: /C:/Users/eburns-admin/Downloads/gaeaplus-master/out/production/gaeaplus-master/si/xlab/gaea/core/shaders/data/Blure7H.glsl
Aug 28, 2013 10:21:47 AM si.xlab.gaea.core.shaders.BasicGLSLCompiler loadProgram
INFO: Compiling shader: /C:/Users/eburns-admin/Downloads/gaeaplus-master/out/production/gaeaplus-master/si/xlab/gaea/core/shaders/data/HDRBloom.glsl
Aug 28, 2013 10:21:47 AM si.xlab.gaea.core.shaders.BasicShaderFactory buildGLSLShader
INFO: Shader loaded: /C:/Users/eburns-admin/Downloads/gaeaplus-master/out/production/gaeaplus-master/si/xlab/gaea/core/shaders/data/HDRBloom.glsl

**Comment by vcucek** [comment]
Problem fixed. 
I will also add AvKeyExt.ENABLE_POS_EFFECTS to enable/disable post-processing effects.
New feature and fix will be available tomorrow.

**Comment by epb-644** [comment]
Awesome, thanks!
